package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"sync"
	"testing"
)

// generatedPuzzle holds a generated board and its optimal move count.
type generatedPuzzle struct {
	pieces  []Piece
	optimal int
	key     string
}

// TestGeneratePresets generates 600+ unique puzzles sorted by increasing
// optimal-move count and writes them to presets.go.
//
// Run with:
//
//	GENERATE_PRESETS=1 go test -run TestGeneratePresets -timeout 30m -count=1
func TestGeneratePresets(t *testing.T) {
	if os.Getenv("GENERATE_PRESETS") == "" {
		t.Skip("Set GENERATE_PRESETS=1 to generate presets.go")
	}

	const (
		maxWorkers = 8
		// Phase 1: mixed difficulties for the first 320 presets.
		mixedPerDiff = 250
		mixedTarget  = 320
		// Phase 2: hard-only for 300 additional presets.
		hardCount  = 1000
		hardTarget = 300
	)

	var mu sync.Mutex
	seen := map[string]bool{}

	// generate launches n goroutines producing boards of difficulty d,
	// deduplicating by canonical state.
	generate := func(d Difficulty, n int) []generatedPuzzle {
		var results []generatedPuzzle
		sem := make(chan struct{}, maxWorkers)
		var wg sync.WaitGroup
		for i := 0; i < n; i++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				sem <- struct{}{}
				defer func() { <-sem }()

				b, opt := NewRandomBoard(d)
				key := encodeState(canonicalize(b.Pieces))

				mu.Lock()
				defer mu.Unlock()
				if !seen[key] {
					seen[key] = true
					results = append(results, generatedPuzzle{
						pieces:  append([]Piece{}, b.Pieces...),
						optimal: opt,
						key:     key,
					})
				}
			}()
		}
		wg.Wait()
		return results
	}

	// Phase 1: mixed difficulties.
	var mixed []generatedPuzzle
	for _, diff := range []Difficulty{Easy, Medium, Hard} {
		got := generate(diff, mixedPerDiff)
		t.Logf("Phase 1 — %s: %d unique puzzles", diff, len(got))
		mixed = append(mixed, got...)
	}

	sort.Slice(mixed, func(i, j int) bool {
		if mixed[i].optimal != mixed[j].optimal {
			return mixed[i].optimal < mixed[j].optimal
		}
		return mixed[i].key < mixed[j].key
	})
	phase1 := selectEvenly(mixed, mixedTarget)
	t.Logf("Phase 1: selected %d presets (optimal %d — %d)",
		len(phase1), phase1[0].optimal, phase1[len(phase1)-1].optimal)

	// Phase 2: hard-only puzzles not already selected.
	phase1Keys := map[string]bool{}
	for _, p := range phase1 {
		phase1Keys[p.key] = true
	}

	hardPuzzles := generate(Hard, hardCount)
	t.Logf("Phase 2 — Hard: %d unique puzzles generated", len(hardPuzzles))

	// Filter out any that were already selected in phase 1.
	var hardOnly []generatedPuzzle
	for _, p := range hardPuzzles {
		if !phase1Keys[p.key] {
			hardOnly = append(hardOnly, p)
		}
	}

	sort.Slice(hardOnly, func(i, j int) bool {
		if hardOnly[i].optimal != hardOnly[j].optimal {
			return hardOnly[i].optimal < hardOnly[j].optimal
		}
		return hardOnly[i].key < hardOnly[j].key
	})
	phase2 := selectEvenly(hardOnly, hardTarget)
	t.Logf("Phase 2: selected %d hard presets (optimal %d — %d)",
		len(phase2), phase2[0].optimal, phase2[len(phase2)-1].optimal)

	// Combine and sort by optimal.
	all := append(phase1, phase2...)
	sort.Slice(all, func(i, j int) bool {
		if all[i].optimal != all[j].optimal {
			return all[i].optimal < all[j].optimal
		}
		return all[i].key < all[j].key
	})

	t.Logf("Total: %d presets (optimal %d — %d)",
		len(all), all[0].optimal, all[len(all)-1].optimal)

	writePresetsFile(t, all)
}

// selectEvenly picks `target` items evenly spaced from a sorted slice.
func selectEvenly[T any](src []T, target int) []T {
	n := len(src)
	if n <= target {
		return src
	}
	out := make([]T, target)
	for i := range target {
		idx := i * (n - 1) / (target - 1)
		out[i] = src[idx]
	}
	return out
}

// writePresetsFile writes the presets.go source file.
func writePresetsFile(t *testing.T, all []generatedPuzzle) {
	t.Helper()

	var sb strings.Builder
	sb.WriteString("// Code generated by TestGeneratePresets; DO NOT EDIT.\n\n")
	sb.WriteString("package main\n\n")
	sb.WriteString(fmt.Sprintf("// presets contains %d pre-generated puzzles sorted by increasing difficulty.\n", len(all)))
	sb.WriteString("var presets = []presetEntry{\n")

	for _, p := range all {
		sb.WriteString(fmt.Sprintf("\t{Optimal: %d, Pieces: []Piece{", p.optimal))
		for j, piece := range p.pieces {
			if j > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("{%s, %d, %d}", pieceKindName(piece.Kind), piece.X, piece.Y))
		}
		sb.WriteString("}},\n")
	}

	sb.WriteString("}\n")

	if err := os.WriteFile("presets.go", []byte(sb.String()), 0o644); err != nil {
		t.Fatalf("Failed to write presets.go: %v", err)
	}
	t.Logf("Wrote presets.go with %d puzzles", len(all))
}

func pieceKindName(k PieceKind) string {
	switch k {
	case Small:
		return "Small"
	case Vertical:
		return "Vertical"
	case Horizontal:
		return "Horizontal"
	case Large:
		return "Large"
	}
	return "?"
}
