package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"sync"
	"testing"
)

// generatedPuzzle holds a generated board and its optimal move count.
type generatedPuzzle struct {
	pieces  []Piece
	optimal int
	key     string
}

// TestGeneratePresets generates 300+ unique puzzles sorted by increasing
// optimal-move count and writes them to presets.go.
//
// Run with:
//
//	GENERATE_PRESETS=1 go test -run TestGeneratePresets -timeout 10m -count=1
func TestGeneratePresets(t *testing.T) {
	if os.Getenv("GENERATE_PRESETS") == "" {
		t.Skip("Set GENERATE_PRESETS=1 to generate presets.go")
	}

	const (
		perDifficulty = 250 // boards to generate per difficulty level
		target        = 320 // desired number of presets
		maxWorkers    = 8
	)

	var mu sync.Mutex
	seen := map[string]bool{}
	var all []generatedPuzzle

	sem := make(chan struct{}, maxWorkers)
	var wg sync.WaitGroup

	for _, diff := range []Difficulty{Easy, Medium, Hard} {
		for i := 0; i < perDifficulty; i++ {
			wg.Add(1)
			go func(d Difficulty) {
				defer wg.Done()
				sem <- struct{}{}
				defer func() { <-sem }()

				b, opt := NewRandomBoard(d)
				key := encodeState(canonicalize(b.Pieces))

				mu.Lock()
				defer mu.Unlock()
				if !seen[key] {
					seen[key] = true
					all = append(all, generatedPuzzle{
						pieces:  append([]Piece{}, b.Pieces...),
						optimal: opt,
						key:     key,
					})
				}
			}(diff)
		}
	}

	wg.Wait()
	t.Logf("Generated %d unique puzzles", len(all))

	// Sort by optimal move count, break ties by canonical key.
	sort.Slice(all, func(i, j int) bool {
		if all[i].optimal != all[j].optimal {
			return all[i].optimal < all[j].optimal
		}
		return all[i].key < all[j].key
	})

	// Select evenly-spaced puzzles from the sorted list.
	selected := selectEvenly(all, target)
	t.Logf("Selected %d presets (optimal range: %d — %d)",
		len(selected), selected[0].optimal, selected[len(selected)-1].optimal)

	writePresetsFile(t, selected)
}

// selectEvenly picks `target` items evenly spaced from a sorted slice.
func selectEvenly[T any](src []T, target int) []T {
	n := len(src)
	if n <= target {
		return src
	}
	out := make([]T, target)
	for i := range target {
		idx := i * (n - 1) / (target - 1)
		out[i] = src[idx]
	}
	return out
}

// writePresetsFile writes the presets.go source file.
func writePresetsFile(t *testing.T, all []generatedPuzzle) {
	t.Helper()

	var sb strings.Builder
	sb.WriteString("// Code generated by TestGeneratePresets; DO NOT EDIT.\n\n")
	sb.WriteString("package main\n\n")
	sb.WriteString(fmt.Sprintf("// presets contains %d pre-generated puzzles sorted by increasing difficulty.\n", len(all)))
	sb.WriteString("var presets = []presetEntry{\n")

	for _, p := range all {
		sb.WriteString(fmt.Sprintf("\t{Optimal: %d, Pieces: []Piece{", p.optimal))
		for j, piece := range p.pieces {
			if j > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("{%s, %d, %d}", pieceKindName(piece.Kind), piece.X, piece.Y))
		}
		sb.WriteString("}},\n")
	}

	sb.WriteString("}\n")

	if err := os.WriteFile("presets.go", []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write presets.go: %v", err)
	}
	t.Logf("Wrote presets.go with %d puzzles", len(all))
}

func pieceKindName(k PieceKind) string {
	switch k {
	case Small:
		return "Small"
	case Vertical:
		return "Vertical"
	case Horizontal:
		return "Horizontal"
	case Large:
		return "Large"
	}
	return "?"
}
